#------------------------------------------------#
#                   MIGRATION                    #
#------------------------------------------------#

#This section is used for migration from other plugins

#The table name of this database (For instance, "alix")
migrate-table-name: authme
# The user/database name
migrate-user: authme
#The user of this database (For instance, "root")
migrate-username: authme
#Connection parameters
migrate-password:
migrate-host:
migrate-port:
# Path to the SQLite file, assuming the starting position in the "plugins" folder
migrate-sqlite-path: "AuthMe/authme.db"

#The maximum lifetime of a database connection (in seconds)
migrate-max-lifetime: 60

#------------------------------------------------#
#                 EXTERNAL SYNC                  #
#------------------------------------------------#

#Defines whether alix should store some of its users.yml data into the database, whose connection parameters are given below
# A copy of the data will still be kept locally
external-sync: false
#Defines the database connector type to use. Available:
# MySQL - supports some MySQL-like databases (for example MariaDB)
# PostgreSQL - uses Postgres
# SQLite - stores data in a locally-defined file, SQL-style
database-type: PostgreSQL
# The user/database name
user: postgres

#The user of this database (For instance, "root")
username:
#Connection parameters
password:
host:
port:
# Path to the SQLite file, assuming the starting position in the "plugins" folder
sqlite-path: "AlixSystem/sqlite.db"

#The maximum lifetime of a database connection (in seconds)
max-lifetime: 60