name: AlixSystem
version: 3.4.0
main: alix.loaders.bukkit.BukkitAlixMain
author: ShadowOfHeaven
api-version: 1.13
loadbefore:
  - packetevents #override it's settings if present
softdepend:
  - SkinsRestorer
  - FastLogin
  - LuckPerms
  - floodgate
  - Essentials #to ensure it loads first, and has it's commands registered first, so that we can potentially override them