#------------------------------------------------------------------------------------#
#                       This is the config.yml file for AlixBungee.                  #
#     If you're curious about certain parameters, you can join our discord server    #
#                         at https://discord.gg/bWjmA7s3xV                           #
#------------------------------------------------------------------------------------#

# coordinator - Requires all backend servers to have the spigot version of AlixSystem installed (https://www.spigotmc.org/resources/alixsystem.109144/).
# A better alternative to this mode is currently being developed.
# Changing  this parameters currently does nothing
mode: coordinator