package alix.common.connection.profiler;

public enum ConnectionStage {

    //limbo connect
    CHANNEL_INIT,
    HA_PROXY_MESSAGE_RECEIVED,
    HA_PROXY_ADDRESS_ASSIGNED,
    HANDSHAKE,
    LOGIN_START,
    STATUS_REQUEST,
    VERDICT_REQUESTED,
    NAME_PASSED,
    HAS_DATA_ALLOWED,
    TRAFFIC_PASSED,
    INDEX_PASSED,
    TRACKER_PASSED,
    VPN_BLOCKING_REQUESTED,
    VPN_EVALUATED,
    VERDICT_REACHED,
    UNINJECT_FINISHED,
    FIRED_LOGIN_SUCCESS,

    //server connect
    SERVER_CONNECT,
    SERVER_HANDSHAKE,
    SERVER_LOGIN_START,
    SERVER_STATUS_REQUEST,
    SERVER_PRE_LOGIN,
    SERVER_ENCRYPTION_REQUEST_SENT,
    SERVER_ENCRYPTION_REQUEST_RECEIVED,
    SERVER_CONTINUE_NO_AUTH,
    SERVER_PREMIUM_REQUEST_BLOCKING,
    SERVER_ADD_TO_VERIFIED_CACHE,
    SERVER_CHOOSE_INITIAL_SERVER,
    SERVER_INIT_AFTER_LOGIN_SUCCESS,

    //disconnect
    TIMED_OUT,
    TOTAL_CONNECTIONS_CNT_LIMIT_REACHED,
    LOCAL_CONNECTIONS_CNT_LIMIT_REACHED,
    CLOSE_INVOKED,
    CLOSE_FUTURE_FINISHED
}