name: AlixSystem
version: 2.8.0
main: alix.loaders.bukkit.BukkitAlixMain
author: ShadowOfHeaven
api-version: 1.13
softdepend:
  - FastLogin
  - LuckPerms
  - packetevents
  - Essentials #to ensure it loads first and has it's commands registered first, so that we can potentially override them
commands:
  as:
    description: Main AlixSystem commands.
    permission: alixsystem.admin