name: AlixSystem
version: 2.7.0 DEV-2
main: alix.loaders.bukkit.BukkitAlixMain
author: ShadowOfHeaven
api-version: 1.13
softdepend:
  - FastLogin
  - LuckPerms
  - packetevents
commands:
  as:
    description: Main AlixSystem commands.
    permission: alixsystem.admin
  fly:
    description: AlixSystem Fly Command.
    permission: alixsystem.fly
  rename:
    description: AlixSystem Rename Command.
    permission: alixsystem.rename
  speed:
    description: AlixSystem Speed Command.
    permission: alixsystem.speed
  heal:
    description: AlixSystem Heal Command.
    permission: alixsystem.heal
  feed:
    description: AlixSystem Feed Command.
    permission: alixsystem.feed
  enderchest:
    description: AlixSystem EnderChest access Command.
    permission: alixsystem.enderchest
  invsee:
    description: AlixSystem InventoryView Command.
    permission: alixsystem.invsee
  gamemode:
    description: AlixSystem Gamemode switch Command.
    permission: alixsystem.gamemode
  list:
    description: AlixSystem PlayerList Command.
    aliases: lista
    permission: alixsystem.list
  nickname:
    description: AlixSystem Nickname Command.
    permission: alixsystem.nickname
  register:
    description: AlixSystem Register Command.
  login:
    description: AlixSystem Login Command.
  changepassword:
    description: AlixSystem Password Change Command.
  captcha:
    description: AlixSystem Captcha Verify Command.
  unban:
    description: AlixSystem Unban Command.
    permission: alixsystem.unban
  unbanip:
    description: AlixSystem UnbanIP Command.
    permission: alixsystem.unbanip
  tempban:
    description: AlixSystem TempBan Command.
    permission: alixsystem.tempban
  tempbanip:
    description: AlixSystem TempIPBan Command.
    permission: alixsystem.tempbanip
  op:
    description: AlixSystem OperatorSet Command.
    permission: alixsystem.op
  deop:
    description: AlixSystem OperatorUnset Command.
    permission: alixsystem.deop
  home:
    description: AlixSystem HomeTeleport Command.
    permission: alixsystem.home
  sethome:
    description: AlixSystem HomeSet Command.
    permission: alixsystem.home
  removehome:
    description: AlixSystem HomeSet Command.
    permission: alixsystem.home
  homelist:
    description: AlixSystem HomeList Command.
    permission: alixsystem.home
  tpa:
    description: AlixSystem Teleport Command.
    permission: alixsystem.tpa
  tpaccept:
    description: AlixSystem Teleport Accept Command.
    permission: alixsystem.tpa
  tpadeny:
    description: AlixSystem Teleport Deny Command.
    permission: alixsystem.tpa
  tpacancel:
    description: AlixSystem Teleport Deny Command.
    permission: alixsystem.tpa
  tpaon:
    description: AlixSystem Teleport Request Receive Set On Command.
    permission: alixsystem.tpa
  tpaoff:
    description: AlixSystem Teleport Request Receive Set Off Command.
    permission: alixsystem.tpa
  mute:
    description: AlixSystem Mute Command
    permission: alixsystem.mute
  unmute:
    description: AlixSystem Unmute Command
    permission: alixsystem.unmute
  warp:
    description: AlixSystem Warp Teleport Command
    permission: alixsystem.warp
  addwarp:
    description: AlixSystem Warp Create Command
    permission: alixsystem.admin.warp
  removewarp:
    description: AlixSystem Warp Remove Command
    permission: alixsystem.admin.warp
  setspawn:
    description: AlixSystem SpawnSet Command
    permission: alixsystem.setspawn
  spawn:
    description: AlixSystem SpawnTeleport Command
    permission: alixsystem.spawn
  msg:
    description: AlixSystem Direct Message Command
  reply:
    description: AlixSystem Reply Command
  chat:
    description: AlixSystem Chat Status Set Command
    permission: alixsystem.admin.chat
  chatclear:
    description: AlixSystem Chat Clear Command
    permission: alixsystem.admin.chatclear
  sudo:
    description: AlixSystem Sudo Command
    permission: alixsystem.sudo